namespace: devopsarr
name: whisparr
# Version will be updated by workflow
version: 0.0.1
readme: README.md
authors:
  - Fuochi (github.com/Fuochi)
description: "Ansible collection for Whisparr"
license_file: LICENSE
tags:
  - whisparr
  - arr
  - movies
repository: https://github.com/devopsarr/ansible-collection-whisparr
#documentation: https://github.com/ansible-collection-migration/devopsarr.whisparr/tree/main/docs
homepage: https://github.com/devopsarr/ansible-collection-whisparr
issues: https://github.com/devopsarr/ansible-collection-whisparr/issues
build_ignore:
  - .gitignore
  - .github/
  - changelogs/.plugin-cache.yaml